INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Уильям Шекспир','26-Apr-1564','23-Apr-1616');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Джек Лондон','12-Jan-1876','22-Nov-1916');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Рэй Брэдбери','22-Aug-1920','5-Jun-2012');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Фрэнсис Скотт Фицджеральд','24-Sept-1896','21-Dec-1940');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Шарлотта Бронте','21-Apr-1816','31-Mar-1855');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Брэм Стокер','8-Nov-1847','20-Apr-1912');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Николай Гоголь','1-Apr-1809','4-Mar-1852');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Герберт Уэллс','21-Sept-1866 ','13-Aug-1946');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Сьюзен Коллинз','30-Nov-1961','');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Дмитрий Глуховский','12-Jun-1979','');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Стиг Ларссон','15-Aug-1954','9-Nov-2004');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Ричард Бах','23-Jun-1936','');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Жюль Верн','8-Feb-1828','24-Mar-1905');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Харуки Мураками','12-Jan-1949','');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Джордж Р. Р. Мартин','20-Sept-1948','');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Виктор Пелевин','22-Nov-1962','');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Владимир Набоков','22-Apr-1899','2-Jul-1977');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Олдос Хаксли','26-Jun-1894','22-Nov-1963');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Маргарет Митчелл','8-Oct-1900','16-Aug-1949');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Александр Дюма','24-Jul-1802','5-Dec-1870');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Януш Леон Вишневский','18-Aug-1954','');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Михаил Булгаков','3-May-1891','10-Mar-1940');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Фёдор Достоевский','30-Oct-1821','28-Jan-1881');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Артур Конан Дойл','22-May-1859','7-Jul-1930');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Джон Фаулз','31-Mar-1926','5-Nov-2005');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Габриэль Гарсиа Маркес','6-Mar-1928','17-Apr-2014');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Иван Тургенев','28-Oct-1818','22-Aug-1883');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Александр Куприн','7-Sept-1870','25-Aug-1938');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Антон Чехов','17-Jan-1860','2-Jul-1904');
INSERT INTO authors(fullname, birth_date, death_date) VALUES ('Дж. К. Роулинг','31-Jul-1965','');
INSERT INTO genres(name) VALUES ('Психоделика');
INSERT INTO genres(name) VALUES ('Реализм');
INSERT INTO genres(name) VALUES ('Фантастика');
INSERT INTO genres(name) VALUES ('Ужасы');
INSERT INTO genres(name) VALUES ('Антиутопия');
INSERT INTO genres(name) VALUES ('Постмодернизм');
INSERT INTO genres(name) VALUES ('Космоопера');
INSERT INTO genres(name) VALUES ('Сюрреализм');
INSERT INTO genres(name) VALUES ('Боевая фантастика');
INSERT INTO genres(name) VALUES ('Фэнтези');
INSERT INTO genres(name) VALUES ('Детектив');
INSERT INTO genres(name) VALUES ('Боевик');
INSERT INTO genres(name) VALUES ('Постапокалипсис');
INSERT INTO genres(name) VALUES ('Магический реализм');
INSERT INTO genres(name) VALUES ('Киберпанк');
INSERT INTO genres(name) VALUES ('Исторические приключения');
INSERT INTO genres(name) VALUES ('Сказка');
INSERT INTO genres(name) VALUES ('Новелла');
INSERT INTO genres(name) VALUES ('Космическая фантастика');
INSERT INTO genres(name) VALUES ('Научная фантастика');
INSERT INTO genres(name) VALUES ('Триллер');
INSERT INTO genres(name) VALUES ('Исторические романы');
INSERT INTO genres(name) VALUES ('Трагедия');
INSERT INTO genres(name) VALUES ('Поэзия');
INSERT INTO books(title, author_id, publication_date, lang) VALUES ('Гамлет','1','1603','eng');
INSERT INTO book_genre(book_id, genre_id) VALUES ('1','1');
INSERT INTO book_genre(book_id, genre_id) VALUES ('1','2');
INSERT INTO cities(name) VALUES('Абакан') ;